apiVersion: v1
kind: Service
metadata:
  name: thinknyxapp-svc
  labels:
    app: thinknyxapp
spec:
  type: NodePort
  selector:
    app: thinknyxapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
