name: call reusable workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: provide an env
        required: true
        type: choice
        options:
          - dev
          - qa
          - stg
          - prod

jobs:
  call-hello:
    uses: ./.github/workflows/reusable-hello.yml
    with:
      environment: ${{inputs.environment}}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
