# The goal is to create a matrix where each environment carries its own configuration
# dev
#  ├── region: us-east-1
#  ├── role: GitHubActions-Dev
#  └── approval: false
# 
# qa
#  ├── region: us-east-1
#  ├── role: GitHubActions-QA
#  └── approval: false
# 
# prod
#  ├── region: eu-west-1
#  ├── role: GitHubActions-PROD
#  └── approval: true

# Create an environment configuration matrix

name: Dynamic Matrix Demo

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ matrix.environment }}

    strategy:
      matrix:
        include:

          - environment: dev
            region: us-east-1
            aws_role: GitHubActions-Dev
            approval_required: false

          - environment: qa
            region: us-east-1
            aws_role: GitHubActions-QA
            approval_required: false

          - environment: prod
            region: eu-west-1
            aws_role: GitHubActions-PROD
            approval_required: true

    steps:

      - name: Show deployment configuration
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "Region: ${{ matrix.region }}"
          echo "AWS Role: ${{ matrix.aws_role }}"
          echo "Approval Required: ${{ matrix.approval_required }}"
      - name: Debug OIDC claims
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TOKEN_JSON=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
      
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r '.value')
      
          PAYLOAD=$(echo "$ID_TOKEN" | cut -d '.' -f2)
      
          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{
            iss,
            aud,
            sub,
            repository,
            repository_owner,
            environment,
            ref,
            ref_type
          }'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::997554581092:role/${{ matrix.aws_role }}
          aws-region: ${{ matrix.region }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity