# The goal is to create a matrix where each environment carries its own configuration
# dev
#  ├── region: us-east-1
#  ├── role: GitHubActions-Dev
#  └── approval: false
# 
# qa
#  ├── region: us-east-1
#  ├── role: GitHubActions-QA
#  └── approval: false
# 
# prod
#  ├── region: eu-west-1
#  ├── role: GitHubActions-PROD
#  └── approval: true

# Create an environment configuration matrix

name: Dynamic Matrix Demo

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:

  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:

          - environment: dev
            region: us-east-1
            aws_role: GitHubActions-Dev
            approval_required: false

          - environment: qa
            region: us-east-1
            aws_role: GitHubActions-QA
            approval_required: false

          - environment: prod
            region: eu-west-1
            aws_role: GitHubActions-PROD
            approval_required: true

    steps:

      - name: Show deployment configuration
        run: |
          echo "Environment: ${{ matrix.environment }}"
          echo "Region: ${{ matrix.region }}"
          echo "AWS Role: ${{ matrix.aws_role }}"
          echo "Approval Required: ${{ matrix.approval_required }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::997554581092:role/${{ matrix.aws_role }}
          aws-region: ${{ matrix.region }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity     