name: My First GitHub Action

on:
  push:
    branches:
      - main
      - deploy-using-kubernetes
    paths:
     - '.github/workflows/first.yml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/first.yml'
  workflow_dispatch: # allows manual runs from the Actions tab
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - qa
          - perf
          - staging
          - production
      action:
        description: Action to perform
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  Repo_info:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name:  print hello
        run: echo "Hello World of gitAction"
      - name: Show repository information
        run: |
          echo "Repository Name: ${{ github.repository }}"
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository URL: ${{ github.server_url }}/${{ github.repository }}"
          echo "Repository Default Branch: ${{ github.event.repository.default_branch }}"
          echo "Repository Visibility: ${{ github.event.repository.visibility }}"
          echo "Repository Created At: ${{ github.event.repository.created_at }}"
          echo "Repository Updated At: ${{ github.event.repository.updated_at }}"
          echo "Repository Actor: ${{ github.actor }}"
      - name: List files in the repository
        run: ls -lR
      - name: show  environment based parameter
        run: |
         echo "Environment: is ${{ inputs.environment }}"
         echo "Action: is ${{ inputs.action }}"
