name: This workflow is a demo for reusable workflows

on: 
  push:
    branches:
      - main
  workflow_dispatch: # allows manual runs from the Actions tab
  pull_request:
    branches:
      - main
permissions:
  actions: read
  contents: read
  security-events: write 
  packages: write

jobs:
  ci-cd-pipeline-job:
    uses: veeroo2011/reusable-workflows/.github/workflows/cicd_workflow.yml@main
    with:
      run_unit_tests: true
      run_codeql: true
      run_sonarqube: false
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy-job-k8s:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: ci-cd-pipeline-job
    environment: staging
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl version
          kubectl get nodes
      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version
      - name: update image name in deployment YAML
        run: |
          IMAGE_TAGS="${{ github.run_id}}-${GITHUB_SHA::7}"
          export IMAGE="thinknyx_app:$IMAGE_TAG:${IMAGE_TAGS}"
          yq e '.spec.template.spec.containers[0].image = strenv(IMAGE)' manifests/deployment.yaml -i
          cat manifests/deployment.yaml
      - name: Create Namesapace if not exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
      - name: Deploy to Kubernetes Cluster
        run: |
          kubectl apply -f manifests/ -n $NAMESPACE
      - name: verify deployment
        run: |
          kubectl rollout status deployment/thinknyxapp -n $NAMESPACE
          kubectl get all -n $NAMESPACE

