name: My First Workflow

on: 
  push:
    branches:
      - develop
      - 'feature-*'
  workflow_dispatch: # allows manual runs from the Actions tab
  # schedule:
  #   - cron: '*/5 * * * *' # run every 5 minutes

jobs:
  Checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: pwd && ls -latr
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List files after checkout
        run: pwd && ls -latr

  Artifacts:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          echo "First artifact $PWD" > artifact.txt
          echo "Extra artifact file" > artifact4.txt
          mkdir -p artifacts
          echo "Second artifact $(date)" > artifacts/artifact2.txt
          echo "Third artifact $(hostname)" > artifacts/artifact3.txt

      - name: Upload single file
        uses: actions/upload-artifact@v4
        with:
          name: single_file
          path: artifact.txt
      - name: Upload multiple file
        uses: actions/upload-artifact@v4
        with:
          name: multiple_file
          path: artifacts/

  Download-Artifacts:
    name: Download Artifacts
    runs-on: ubuntu-latest
    needs: Artifacts
    steps:
      - name: Check files before download
        run: pwd && ls -ltr
      - name: Download multiple-path artifact
        uses: actions/download-artifact@v4
        with:
          name: single_file
      - name: Check files after download
        run: pwd && ls -ltr

  Download-Artifacts-Custom-path:
    name: Download Artifacts to Custom Path
    runs-on: ubuntu-latest
    needs: Artifacts
    steps:
      - name: Create custom directories
        run: |
          mkdir -p single_file
          mkdir -p multiple-dir
      - name: Download single_file artifact
        uses: actions/download-artifact@v4
        with:
          name: multiple_file
          path: multiple-dir

