name: My First Workflow

on: 
  push:
    branches:
      - main
  workflow_dispatch: # allows manual runs from the Actions tab
  pull_request:
    branches:
      - main

jobs:
  github-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: show hostname 
        run: |
          echo "Hello World"
          hostname
          hostname -i
          uname -a
  self-hosted:
    runs-on: self-hosted
    steps:
      - name: show hostname 
        run: |
          echo "Hello World on self-hosted runner"
          sw_vers
          hostname -s
          uname -a       
      
    