name: Reusable Hello

on:
  workflow_call:
    inputs:
      environment:
        description: provide an env
        required: true
        type: string

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: |
          echo "hello from reusable workflow"
          echo "env selected is ${{inputs.environment}}"
  