name: OIDC token

on:
  workflow_dispatch:

permissions: # it allow to request OIDC token from the GitHub Actions runner
  id-token: write
  contents: read

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - name: print github reference
        run: |
          echo "${{ github.repository }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.actor }}"
          echo "${{ github.event_name }}"
      - name: checkout repository
        uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::997554581092:role/GitHubActionsDemoRole
          aws-region: us-east-1
      - name: Verfiy AWS identity
        run: |
          aws sts get-caller-identity
      - name: Check S3 bucket objects
        run: |
          aws s3 ls