name: Access aws resource using OIDC token

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select Environment to deploy
        required: true
        type: choice
        options:
          - Dev
          - QA
          - PROD

permissions: # it allow to request OIDC token from the GitHub Actions runner
  id-token: write
  contents: read

jobs:
  token:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: Debug OIDC claims
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TOKEN_JSON=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
      
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r '.value')
      
          PAYLOAD=$(echo "$ID_TOKEN" | cut -d '.' -f2)
      
          echo "$PAYLOAD" | base64 -d 2>/dev/null | jq '{
            iss,
            aud,
            sub,
            repository,
            repository_owner,
            environment,
            ref,
            ref_type
          }'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::997554581092:role/GitHubActions-${{ inputs.environment}}
          aws-region: us-east-1
      - name: Verify AWS identity
        run: |
          echo "GitHub Environment: ${{ inputs.environment }}"
          aws sts get-caller-identity
      - name: Check S3 bucket objects
        run: |
          aws s3 ls